const defaultRuleValue = 'error';
module.exports.ruleNames = [
  // eslint-plugin-jest [release](https://github.com/jest-community/eslint-plugin-jest/releases)
  // [v28.8.3]

  // #region [Rules](https://github.com/jest-community/eslint-plugin-jest?tab=readme-ov-file#rules)
  'jest/consistent-test-it',
  'jest/expect-expect',
  'jest/max-expects',
  'jest/max-nested-describe',
  'jest/no-alias-methods',
  'jest/no-commented-out-tests',
  'jest/no-conditional-expect',
  'jest/no-conditional-in-test',
  'jest/no-confusing-set-timeout',
  'jest/no-deprecated-functions',
  'jest/no-disabled-tests',
  'jest/no-done-callback',
  'jest/no-duplicate-hooks',
  'jest/no-export',
  'jest/no-focused-tests',
  'jest/no-hooks',
  'jest/no-identical-title',
  'jest/no-interpolation-in-snapshots',
  'jest/no-jasmine-globals',
  'jest/no-large-snapshots',
  'jest/no-mocks-import',
  'jest/no-restricted-jest-methods',
  'jest/no-restricted-matchers',
  'jest/no-standalone-expect',
  'jest/no-test-prefixes',
  'jest/no-test-return-statement',
  'jest/no-untyped-mock-factory',
  'jest/padding-around-after-all-blocks',
  'jest/padding-around-after-each-blocks',
  'jest/padding-around-all',
  'jest/padding-around-before-all-blocks',
  'jest/padding-around-before-each-blocks',
  'jest/padding-around-describe-blocks',
  'jest/padding-around-expect-groups',
  'jest/padding-around-test-blocks',
  'jest/prefer-called-with',
  'jest/prefer-comparison-matcher',
  'jest/prefer-each',
  'jest/prefer-equality-matcher',
  'jest/prefer-expect-assertions',
  'jest/prefer-expect-resolves',
  'jest/prefer-hooks-in-order',
  'jest/prefer-hooks-on-top',
  'jest/prefer-importing-jest-globals',
  'jest/prefer-jest-mocked',
  'jest/prefer-lowercase-title',
  'jest/prefer-mock-promise-shorthand',
  'jest/prefer-snapshot-hint',
  'jest/prefer-spy-on',
  'jest/prefer-strict-equal',
  'jest/prefer-to-be',
  'jest/prefer-to-contain',
  'jest/prefer-to-have-length',
  'jest/prefer-todo',
  'jest/require-hook',
  'jest/require-to-throw-message',
  'jest/require-top-level-describe',
  'jest/valid-describe-callback',
  'jest/valid-expect',
  'jest/valid-expect-in-promise',
  'jest/valid-title',
  // #endregion Rules

  // #region [Requires Type Checking](https://github.com/jest-community/eslint-plugin-jest?tab=readme-ov-file#requires-type-checking)
  // 'jest/unbound-method',
  // #endregion Requires Type Checking
];

module.exports.rules = Object.fromEntries(module.exports.ruleNames.map((ruleName) => [ ruleName, defaultRuleValue ]));
